// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1ecvnLO94Q7NUFT3liol-WDbUT7wBXM',
    appId: '1:1075434774461:web:nepika-web-app',
    messagingSenderId: '1075434774461',
    projectId: 'nepika-ai',
    authDomain: 'nepika-ai.firebaseapp.com',
    storageBucket: 'nepika-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFuWhBP7pxyxb-wPudX-ZL79U5Lw9wr8',
    appId: '1:1075434774461:android:0805973ab36af68f05bcd4',
    messagingSenderId: '1075434774461',
    projectId: 'nepika-ai',
    storageBucket: 'nepika-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1ecvnLO94Q7NUFT3liol-WDbUT7wBXM',
    appId: '1:1075434774461:ios:3431aedde55c9f4f05bcd4',
    messagingSenderId: '1075434774461',
    projectId: 'nepika-ai',
    storageBucket: 'nepika-ai.firebasestorage.app',
    iosBundleId: 'com.assisted.nepika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1ecvnLO94Q7NUFT3liol-WDbUT7wBXM',
    appId: '1:1075434774461:ios:3431aedde55c9f4f05bcd4',
    messagingSenderId: '1075434774461',
    projectId: 'nepika-ai',
    storageBucket: 'nepika-ai.firebasestorage.app',
    iosBundleId: 'com.assisted.nepika',
  );
}