// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1v33JhBQA56GiohKMlMzPs7o7KdRQENc',
    appId: '1:443222788965:web:bb4a6e19cff7a57c106f8c',
    messagingSenderId: '443222788965',
    projectId: 'nepika-87cc7',
    authDomain: 'nepika-87cc7.firebaseapp.com',
    storageBucket: 'nepika-87cc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-6KHY2ZP6Y-Bb44Jas0I7KjdN_LxM4Y',
    appId: '1:429514031239:android:0ac5a35299da86a3577822',
    messagingSenderId: '429514031239',
    projectId: 'nepika-c189e',
    storageBucket: 'nepika-c189e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuAQ_972NTH0lzDY5GJvzbCaReFg2GoU',
    appId: '1:429514031239:ios:8309989be3164a00577822',
    messagingSenderId: '429514031239',
    projectId: 'nepika-c189e',
    storageBucket: 'nepika-c189e.firebasestorage.app',
    iosBundleId: 'com.assisted.nepika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILTnmXHnkvsU4sTI822IsyqcznFZOCCQ',
    appId: '1:443222788965:ios:ac1db9d43fc57629106f8c',
    messagingSenderId: '443222788965',
    projectId: 'nepika-87cc7',
    storageBucket: 'nepika-87cc7.firebasestorage.app',
    iosBundleId: 'com.assisted.nepika',
  );
}